### PR TITLE
Issue 100 MapBox

### PR DESCRIPTION
**Pull request by chohyeonkim**
## :: Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Edit convention

<br />

## :: Description
image

image

<br />

### CODE REVIEW

**Comment by jieunkxx** [comment]
@chohyeonkim could you reduce the width to the same as the property image box? Thanks!

**Comment by jieunkxx** [comment]
@chohyeonkim in my local I am able to load the detail page. please refer the screenshot below.
Screenshot 2023-07-25 at 6 28 31 PM

**Comment by chohyeonkim** [comment]
> @chohyeonkim in my local I am able to load the detail page. please refer the screenshot below. Screenshot 2023-07-25 at 6 28 31 PM

Do you happen to use Mock data now? then need to change 
ZILLOW_API_LISTING='on' 
ZILLOW_API_PROPERTY_DETAIL='on'

**Comment by chohyeonkim** [comment]
> @chohyeonkim could you reduce the width to the same as the property image box? Thanks!

fixed now ! i will also resolve the merge conflict later

**Pull request closed without merging**
